# Generated by Django 3.0.8 on 2020-08-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200802_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='id',
            new_name='formid',
        ),
    ]
