# Generated by Django 3.1 on 2020-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200802_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
