# Generated by Django 3.1 on 2020-09-16 14:44

import apps.form.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_form_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('responseid', models.CharField(default=apps.form.models.get_response_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='form.form')),
            ],
        ),
    ]
